export const worldLanguages = [
  // Major World Languages
  { id: "en", name: "English", flag: null, isDefault: true, isActive: true },
  { id: "id", name: "Bahasa Indonesia", flag: "🇮🇩", isDefault: false, isActive: true },
  {
    id: "zh",
    name: "Chinese (Mandarin)",
    flag: "🇨🇳",
    isDefault: false,
    isActive: true,
  },
  { id: "hi", name: "Hindi", flag: "🇮🇳", isDefault: false, isActive: true },
  { id: "es", name: "Spanish", flag: "🇪🇸", isDefault: false, isActive: true },
  { id: "ar", name: "Arabic", flag: "🇸🇦", isDefault: false, isActive: true },
  {
    id: "pt",
    name: "Portuguese",
    flag: "🇵🇹",
    isDefault: false,
    isActive: true,
  },
  { id: "ru", name: "Russian", flag: "🇷🇺", isDefault: false, isActive: true },
  { id: "ja", name: "Japanese", flag: "🇯🇵", isDefault: false, isActive: true },
  { id: "fr", name: "French", flag: "🇫🇷", isDefault: false, isActive: true },
  { id: "de", name: "German", flag: "🇩🇪", isDefault: false, isActive: true },
  { id: "ko", name: "Korean", flag: "🇰🇷", isDefault: false, isActive: true },
  { id: "tr", name: "Turkish", flag: "🇹🇷", isDefault: false, isActive: true },
  { id: "it", name: "Italian", flag: "🇮🇹", isDefault: false, isActive: true },
  { id: "th", name: "Thai", flag: "🇹🇭", isDefault: false, isActive: true },
  {
    id: "vi",
    name: "Vietnamese",
    flag: "🇻🇳",
    isDefault: false,
    isActive: true,
  },
  { id: "pl", name: "Polish", flag: "🇵🇱", isDefault: false, isActive: true },
  { id: "nl", name: "Dutch", flag: "🇳🇱", isDefault: false, isActive: true },
  { id: "uk", name: "Ukrainian", flag: "🇺🇦", isDefault: false, isActive: true },
  { id: "fa", name: "Persian", flag: "🇮🇷", isDefault: false, isActive: true },

  // Africa
  { id: "af", name: "Afrikaans", flag: "🇿🇦", isDefault: false, isActive: true },
  { id: "am", name: "Amharic", flag: "🇪🇹", isDefault: false, isActive: true },
  { id: "sw", name: "Swahili", flag: "🇰🇪", isDefault: false, isActive: true },
  { id: "ha", name: "Hausa", flag: "🇳🇬", isDefault: false, isActive: true },
  { id: "yo", name: "Yoruba", flag: "🇳🇬", isDefault: false, isActive: true },
  { id: "ig", name: "Igbo", flag: "🇳🇬", isDefault: false, isActive: true },
  { id: "zu", name: "Zulu", flag: "🇿🇦", isDefault: false, isActive: true },
  { id: "xh", name: "Xhosa", flag: "🇿🇦", isDefault: false, isActive: true },
  { id: "so", name: "Somali", flag: "🇸🇴", isDefault: false, isActive: true },
  {
    id: "rw",
    name: "Kinyarwanda",
    flag: "🇷🇼",
    isDefault: false,
    isActive: true,
  },
  { id: "mg", name: "Malagasy", flag: "🇲🇬", isDefault: false, isActive: true },

  // Europe
  { id: "sv", name: "Swedish", flag: "🇸🇪", isDefault: false, isActive: true },
  { id: "no", name: "Norwegian", flag: "🇳🇴", isDefault: false, isActive: true },
  { id: "da", name: "Danish", flag: "🇩🇰", isDefault: false, isActive: true },
  { id: "fi", name: "Finnish", flag: "🇫🇮", isDefault: false, isActive: true },
  { id: "cs", name: "Czech", flag: "🇨🇿", isDefault: false, isActive: true },
  { id: "sk", name: "Slovak", flag: "🇸🇰", isDefault: false, isActive: true },
  { id: "hu", name: "Hungarian", flag: "🇭🇺", isDefault: false, isActive: true },
  { id: "ro", name: "Romanian", flag: "🇷🇴", isDefault: false, isActive: true },
  { id: "bg", name: "Bulgarian", flag: "🇧🇬", isDefault: false, isActive: true },
  { id: "hr", name: "Croatian", flag: "🇭🇷", isDefault: false, isActive: true },
  { id: "sr", name: "Serbian", flag: "🇷🇸", isDefault: false, isActive: true },
  { id: "bs", name: "Bosnian", flag: "🇧🇦", isDefault: false, isActive: true },
  { id: "sl", name: "Slovenian", flag: "🇸🇮", isDefault: false, isActive: true },
  {
    id: "mk",
    name: "Macedonian",
    flag: "🇲🇰",
    isDefault: false,
    isActive: true,
  },
  { id: "sq", name: "Albanian", flag: "🇦🇱", isDefault: false, isActive: true },
  { id: "el", name: "Greek", flag: "🇬🇷", isDefault: false, isActive: true },
  { id: "mt", name: "Maltese", flag: "🇲🇹", isDefault: false, isActive: true },
  { id: "is", name: "Icelandic", flag: "🇮🇸", isDefault: false, isActive: true },
  { id: "ga", name: "Irish", flag: "🇮🇪", isDefault: false, isActive: true },
  { id: "cy", name: "Welsh", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", isDefault: false, isActive: true },
  { id: "et", name: "Estonian", flag: "🇪🇪", isDefault: false, isActive: true },
  { id: "lv", name: "Latvian", flag: "🇱🇻", isDefault: false, isActive: true },
  {
    id: "lt",
    name: "Lithuanian",
    flag: "🇱🇹",
    isDefault: false,
    isActive: true,
  },
  {
    id: "be",
    name: "Belarusian",
    flag: "🇧🇾",
    isDefault: false,
    isActive: true,
  },
  { id: "md", name: "Moldovan", flag: "🇲🇩", isDefault: false, isActive: true },

  // Asia
  { id: "bn", name: "Bengali", flag: "🇧🇩", isDefault: false, isActive: true },
  { id: "ur", name: "Urdu", flag: "🇵🇰", isDefault: false, isActive: true },
  { id: "ta", name: "Tamil", flag: "🇱🇰", isDefault: false, isActive: true },
  { id: "si", name: "Sinhala", flag: "🇱🇰", isDefault: false, isActive: true },
  { id: "my", name: "Burmese", flag: "🇲🇲", isDefault: false, isActive: true },
  { id: "km", name: "Khmer", flag: "🇰🇭", isDefault: false, isActive: true },
  { id: "lo", name: "Lao", flag: "🇱🇦", isDefault: false, isActive: true },
  { id: "mn", name: "Mongolian", flag: "🇲🇳", isDefault: false, isActive: true },
  { id: "ne", name: "Nepali", flag: "🇳🇵", isDefault: false, isActive: true },
  { id: "dz", name: "Dzongkha", flag: "🇧🇹", isDefault: false, isActive: true },
  { id: "ka", name: "Georgian", flag: "🇬🇪", isDefault: false, isActive: true },
  { id: "hy", name: "Armenian", flag: "🇦🇲", isDefault: false, isActive: true },
  {
    id: "az",
    name: "Azerbaijani",
    flag: "🇦🇿",
    isDefault: false,
    isActive: true,
  },
  { id: "kk", name: "Kazakh", flag: "🇰🇿", isDefault: false, isActive: true },
  { id: "ky", name: "Kyrgyz", flag: "🇰🇬", isDefault: false, isActive: true },
  { id: "tg", name: "Tajik", flag: "🇹🇯", isDefault: false, isActive: true },
  { id: "tk", name: "Turkmen", flag: "🇹🇲", isDefault: false, isActive: true },
  { id: "uz", name: "Uzbek", flag: "🇺🇿", isDefault: false, isActive: true },
  { id: "ps", name: "Pashto", flag: "🇦🇫", isDefault: false, isActive: true },
  { id: "he", name: "Hebrew", flag: "🇮🇱", isDefault: false, isActive: true },

  // Southeast Asia & Pacific
  { id: "ms", name: "Malay", flag: "🇲🇾", isDefault: false, isActive: true },
  { id: "tl", name: "Filipino", flag: "🇵🇭", isDefault: false, isActive: true },
  { id: "haw", name: "Hawaiian", flag: "🇺🇸", isDefault: false, isActive: true },
  { id: "fj", name: "Fijian", flag: "🇫🇯", isDefault: false, isActive: true },
  { id: "sm", name: "Samoan", flag: "🇼🇸", isDefault: false, isActive: true },
  { id: "to", name: "Tongan", flag: "🇹🇴", isDefault: false, isActive: true },
  { id: "tvl", name: "Tuvaluan", flag: "🇹🇻", isDefault: false, isActive: true },
  { id: "pau", name: "Palauan", flag: "🇵🇼", isDefault: false, isActive: true },
  {
    id: "mh",
    name: "Marshallese",
    flag: "🇲🇭",
    isDefault: false,
    isActive: true,
  },
  { id: "na", name: "Nauruan", flag: "🇳🇷", isDefault: false, isActive: true },

  // Americas
  { id: "qu", name: "Quechua", flag: "🇵🇪", isDefault: false, isActive: true },
  { id: "gn", name: "Guarani", flag: "🇵🇾", isDefault: false, isActive: true },
  { id: "ay", name: "Aymara", flag: "🇧🇴", isDefault: false, isActive: true },
  {
    id: "ht",
    name: "Haitian Creole",
    flag: "🇭🇹",
    isDefault: false,
    isActive: true,
  },

  // Middle East
  { id: "ku", name: "Kurdish", flag: "🇮🇶", isDefault: false, isActive: true },

  // African Countries (additional)
  { id: "sn", name: "Shona", flag: "🇿🇼", isDefault: false, isActive: true },
  { id: "ny", name: "Chichewa", flag: "🇲🇼", isDefault: false, isActive: true },
  { id: "ts", name: "Tsonga", flag: "🇿🇦", isDefault: false, isActive: true },
  { id: "ve", name: "Venda", flag: "🇿🇦", isDefault: false, isActive: true },
  { id: "ss", name: "Swati", flag: "🇸🇿", isDefault: false, isActive: true },
  { id: "st", name: "Sotho", flag: "🇱🇸", isDefault: false, isActive: true },
  { id: "tn", name: "Tswana", flag: "🇧🇼", isDefault: false, isActive: true },
  {
    id: "nd",
    name: "Northern Ndebele",
    flag: "🇿🇼",
    isDefault: false,
    isActive: true,
  },
  { id: "ti", name: "Tigrinya", flag: "🇪🇷", isDefault: false, isActive: true },
  { id: "om", name: "Oromo", flag: "🇪🇹", isDefault: false, isActive: true },

  // Additional Pacific Languages
  { id: "bi", name: "Bislama", flag: "🇻🇺", isDefault: false, isActive: true },
  { id: "ho", name: "Hiri Motu", flag: "🇵🇬", isDefault: false, isActive: true },
  {
    id: "tpi",
    name: "Tok Pisin",
    flag: "🇵🇬",
    isDefault: false,
    isActive: true,
  },

  // Additional European Languages
  {
    id: "lb",
    name: "Luxembourgish",
    flag: "🇱🇺",
    isDefault: false,
    isActive: true,
  },
  { id: "rm", name: "Romansh", flag: "🇨🇭", isDefault: false, isActive: true },
  {
    id: "se",
    name: "Northern Sami",
    flag: "🇳🇴",
    isDefault: false,
    isActive: true,
  },
  { id: "fo", name: "Faroese", flag: "🇫🇴", isDefault: false, isActive: true },
  {
    id: "kl",
    name: "Greenlandic",
    flag: "🇬🇱",
    isDefault: false,
    isActive: true,
  },

  // Additional Asian Languages
  { id: "ug", name: "Uyghur", flag: "🇨🇳", isDefault: false, isActive: true },
  { id: "bo", name: "Tibetan", flag: "🇨🇳", isDefault: false, isActive: true },
  {
    id: "ii",
    name: "Sichuan Yi",
    flag: "🇨🇳",
    isDefault: false,
    isActive: true,
  },
];
